### ISSUE TITLE
NOT NULL constraint failed for query_prototype_queryfieldsmodel.age_lower

### ISSUE THREAD

**Issue by jarmoza** [neurodatascience/concept_query#42]
There appears to be an issue in saving the form data for the age fields.

https://dpaste.com/EUACN8BZY

**Comment by jarmoza** [comment]
@surchs FYI dpaste deletes in 24 hours.

```
Environment:


Request Method: POST
Request URL: http://127.0.0.1:8000/query_prototype/form/

Django Version: 3.2.9
Python Version: 3.9.7
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'query_prototype',
 'crispy_forms',
 'crispy_bootstrap5']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/Users/peregrinepickle/.virtualenvs/concept_query_demo-v7VIQESW/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/peregrinepickle/.virtualenvs/concept_query_demo-v7VIQESW/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)

The above exception (NOT NULL constraint failed: query_prototype_queryfieldsmodel.age_lower) was the direct cause of the following exception:
  File "/Users/peregrinepickle/.virtualenvs/concept_query_demo-v7VIQESW/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/peregrinepickle/.virtualenvs/concept_query_demo-v7VIQESW/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/peregrinepickle/Documents/work/origami/projects/concept_query_demo/query_prototype/views.py", line 176, in formgenerated_query
    query_model_instance.save()
  File "/Users/peregrinepickle/.virtualenvs/concept_query_demo-v7VIQESW/lib/python3.9/site-packages/django/db/models/base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/Users/peregrinepickle/.virtualenvs/concept_query_demo-v7VIQESW/lib/python3.9/site-packages/django/db/models/base.py", line 763, in save_base
    updated = self._save_table(
  File "/Users/peregrinepickle/.virtualenvs/concept_query_demo-v7VIQESW/lib/python3.9/site-packages/django/db/models/base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/Users/peregrinepickle/.virtualenvs/concept_query_demo-v7VIQESW/lib/python3.9/site-packages/django/db/models/base.py", line 906, in _do_insert
    return manager._insert(
  File "/Users/peregrinepickle/.virtualenvs/concept_query_demo-v7VIQESW/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/peregrinepickle/.virtualenvs/concept_query_demo-v7VIQESW/lib/python3.9/site-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/Users/peregrinepickle/.virtualenvs/concept_query_demo-v7VIQESW/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/Users/peregrinepickle/.virtualenvs/concept_query_demo-v7VIQESW/lib/python3.9/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/Users/peregrinepickle/.virtualenvs/concept_query_demo-v7VIQESW/lib/python3.9/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/peregrinepickle/.virtualenvs/concept_query_demo-v7VIQESW/lib/python3.9/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/peregrinepickle/.virtualenvs/concept_query_demo-v7VIQESW/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/peregrinepickle/.virtualenvs/concept_query_demo-v7VIQESW/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/peregrinepickle/.virtualenvs/concept_query_demo-v7VIQESW/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/peregrinepickle/.virtualenvs/concept_query_demo-v7VIQESW/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute
    return Database.Cursor.execute(self, query, params)

Exception Type: IntegrityError at /query_prototype/form/
Exception Value: NOT NULL constraint failed: query_prototype_queryfieldsmodel.age_lower

```

**Comment by jarmoza** [comment]
Should be fixed by https://github.com/neurodatascience/concept_query/pull/36/commits/9152080395db96cafd52a12458238b71d86c0d74

Will wait for further testing before closing.

**Comment by jarmoza** [comment]
This error is no longer occurring thanks the FloatField fix in https://github.com/neurodatascience/concept_query/commit/9152080395db96cafd52a12458238b71d86c0d74
